require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RosterSpotsController do

  # This should return the minimal set of attributes required to create a valid
  # RosterSpot. As you add validations to RosterSpot, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "draft_roster_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RosterSpotsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all roster_spots as @roster_spots" do
      roster_spot = RosterSpot.create! valid_attributes
      get :index, {}, valid_session
      assigns(:roster_spots).should eq([roster_spot])
    end
  end

  describe "GET show" do
    it "assigns the requested roster_spot as @roster_spot" do
      roster_spot = RosterSpot.create! valid_attributes
      get :show, {:id => roster_spot.to_param}, valid_session
      assigns(:roster_spot).should eq(roster_spot)
    end
  end

  describe "GET new" do
    it "assigns a new roster_spot as @roster_spot" do
      get :new, {}, valid_session
      assigns(:roster_spot).should be_a_new(RosterSpot)
    end
  end

  describe "GET edit" do
    it "assigns the requested roster_spot as @roster_spot" do
      roster_spot = RosterSpot.create! valid_attributes
      get :edit, {:id => roster_spot.to_param}, valid_session
      assigns(:roster_spot).should eq(roster_spot)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RosterSpot" do
        expect {
          post :create, {:roster_spot => valid_attributes}, valid_session
        }.to change(RosterSpot, :count).by(1)
      end

      it "assigns a newly created roster_spot as @roster_spot" do
        post :create, {:roster_spot => valid_attributes}, valid_session
        assigns(:roster_spot).should be_a(RosterSpot)
        assigns(:roster_spot).should be_persisted
      end

      it "redirects to the created roster_spot" do
        post :create, {:roster_spot => valid_attributes}, valid_session
        response.should redirect_to(RosterSpot.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved roster_spot as @roster_spot" do
        # Trigger the behavior that occurs when invalid params are submitted
        RosterSpot.any_instance.stub(:save).and_return(false)
        post :create, {:roster_spot => { "draft_roster_id" => "invalid value" }}, valid_session
        assigns(:roster_spot).should be_a_new(RosterSpot)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RosterSpot.any_instance.stub(:save).and_return(false)
        post :create, {:roster_spot => { "draft_roster_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested roster_spot" do
        roster_spot = RosterSpot.create! valid_attributes
        # Assuming there are no other roster_spots in the database, this
        # specifies that the RosterSpot created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RosterSpot.any_instance.should_receive(:update_attributes).with({ "draft_roster_id" => "1" })
        put :update, {:id => roster_spot.to_param, :roster_spot => { "draft_roster_id" => "1" }}, valid_session
      end

      it "assigns the requested roster_spot as @roster_spot" do
        roster_spot = RosterSpot.create! valid_attributes
        put :update, {:id => roster_spot.to_param, :roster_spot => valid_attributes}, valid_session
        assigns(:roster_spot).should eq(roster_spot)
      end

      it "redirects to the roster_spot" do
        roster_spot = RosterSpot.create! valid_attributes
        put :update, {:id => roster_spot.to_param, :roster_spot => valid_attributes}, valid_session
        response.should redirect_to(roster_spot)
      end
    end

    describe "with invalid params" do
      it "assigns the roster_spot as @roster_spot" do
        roster_spot = RosterSpot.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RosterSpot.any_instance.stub(:save).and_return(false)
        put :update, {:id => roster_spot.to_param, :roster_spot => { "draft_roster_id" => "invalid value" }}, valid_session
        assigns(:roster_spot).should eq(roster_spot)
      end

      it "re-renders the 'edit' template" do
        roster_spot = RosterSpot.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RosterSpot.any_instance.stub(:save).and_return(false)
        put :update, {:id => roster_spot.to_param, :roster_spot => { "draft_roster_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested roster_spot" do
      roster_spot = RosterSpot.create! valid_attributes
      expect {
        delete :destroy, {:id => roster_spot.to_param}, valid_session
      }.to change(RosterSpot, :count).by(-1)
    end

    it "redirects to the roster_spots list" do
      roster_spot = RosterSpot.create! valid_attributes
      delete :destroy, {:id => roster_spot.to_param}, valid_session
      response.should redirect_to(roster_spots_url)
    end
  end

end
